### ISSUE TITLE
GTK error with updated OpenCV

### ISSUE THREAD

**Issue by j5207** [danyu9394/linux_camera_tool#9]
Hi,

I've rebuild OpenCV with gtk 2.0 disabled, as shown in the readme file. However, I still have the gtk error. When I run `ldd leopard_cam | grep opencv`, I could get 
`libopencv_highgui.so.4.1 => /home/ji.han/camera/opencv/build/lib/libopencv_highgui.so.4.1 (0x00007fc149fd3000)
	libopencv_imgcodecs.so.4.1 => /home/ji.han/camera/opencv/build/lib/libopencv_imgcodecs.so.4.1 (0x00007fc14834c000)
	libopencv_imgproc.so.4.1 => /home/ji.han/camera/opencv/build/lib/libopencv_imgproc.so.4.1 (0x00007fc146a2d000)
	libopencv_core.so.4.1 => /home/ji.han/camera/opencv/build/lib/libopencv_core.so.4.1 (0x00007fc1456b6000)`
which seems the exeutable have linked to my customize built repo. Thus I'm confused why the GTK error still occurs. Would you mind help me out of this?

Thanks,
Ji

**Comment by danyu9394** [comment]
Hi, 
since there were many people have the issue of opencv gtk3, I built a opencv image and post on docker hub, you can refer to the readme here [on](https://github.com/danyu9394/linux_camera_tool/tree/master/docker) how to run this camera tool on docker. It doesn't affect the speed or anything and is pretty easy to set up.

**Comment by j5207** [comment]
Hi, 

I just remove all the GTK2 and install GTK3 and solve the issue in brute force. Thanks
